#!/usr/bin/env python3
import os
import sys
import platform
import argparse
import shutil
import pathlib
from functools import partial

def dry_symlink(src, target):
    if target.exists():
        print(f'{target} already exists')
        return

    rel_src = os.path.relpath(src, target.parent)
    print(f'Linking {rel_src} -> {target}')


def dry_remove(src, target):
    if target.exists():
        if target.is_symlink():
            if target.samefile(src):
                print(f'Removing {src} -> {target}')
            else:
                print(f'{target} is not a symlink to {src}')
        else:
            print(f'{target} is not a symlink file')


def dry_run(src):
    print(f'Execute: {src}')


def my_symlink(src, target):
    if target.parent != target:
        target.parent.mkdir(parents=True, exist_ok=True)

    if target.exists():
        if target.samefile(src):
            raise Exception(f'Target already exists: {target}')
        else:
            return

    rel_src = os.path.relpath(src, os.path.dirname(target))
    os.symlink(rel_src, target)


def my_remove(src, target):
    if target.exists():
        if target.is_symlink():
            if target.samefile(src):
                target.unlink()
            else:
                raise Exception(f'Target is not a symlink to {src}')
        else:
            raise Exception(f'Target is not a symlink: {target}')


def force_remove(src, target):
    if target.exists():
        if target.is_symlink():
            target.unlink()
        elif target.is_file():
            if not target.samefile(src):
                target.unlink()
            else:
                raise Exception(f'{target} and {src} are in the same directory')
        elif target.is_dir():
            if not target.samefile(src):
                shutil.rmtree(target)
            else:
                raise Exception(f'{target} and {src} are the same directory')
        else:
            raise Exception(f'{target} is not a file or directory')

        return
    else:
        try:
            os.remove(target)
        except FileNotFoundError:
            pass


def my_run(src):
    os.system(src)


def perform_relink(src, target, symlink_func, remove_func):
    remove_func(src, target)
    symlink_func(src, target)


def link_dir(src, target, ignores, action_func, run_func=None, depth=0):
    if not src.is_dir():
        raise Exception(f'{src} is not a directory')

    names = [x.name for x in src.iterdir() if not (depth == 0 and x == src / 'install.sh') \
            and not any(x.match(ignore) for ignore in ignores)]

    for name in names:
        targetname = name

        dot_prefix = '.'
        if platform.system() == 'Windows':
            dot_prefix = '_'

        if targetname.startswith('dot-'):
            targetname = targetname.replace('dot-', dot_prefix, 1)
        elif targetname.startswith('_'):
            targetname = targetname.replace('_', dot_prefix, 1)

        platforms=["@darwin", "@linux", "@windows"]
        if any(targetname.endswith(p) for p in platforms):
            current_platform = platform.system().lower()
            if targetname.endswith(f'@{current_platform}'):
                targetname = targetname.removesuffix(f'@{current_platform}')
            else:
                continue

        entry = src / name

        if entry.is_file() or entry.is_symlink():
            action_func(entry, target / targetname)
        elif entry.is_dir():
            link_dir(entry, target / targetname, ignores, action_func, run_func, depth+1)
        else:
            raise Exception(f'{entry.name} is not a file or directory')

    if depth == 0 and run_func:
        install = src / 'install.sh'
        if install.is_file() and os.access(install, os.X_OK):
            run_func(f'cd {src.name} && ./install.sh')


def main():
    parser = argparse.ArgumentParser(description='Create dotfiles symlink to from directories', formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    group = parser.add_mutually_exclusive_group()
    group.add_argument('-d', '--unlink', dest='unlink', action='store_true', default=False, help='unlink')
    group.add_argument('-r', '--relink', dest='relink', action='store_true', default=False, help='relink')

    group = parser.add_mutually_exclusive_group()
    group.add_argument('--dry-run', dest='dry_run', action='store_true', default=False, help='dry run')
    group.add_argument('--force', dest='force', action='store_true', default=False, help='force link, if target exists delete it first')

    parser.add_argument('--ignore', dest='ignore', action='append', default=["README.*", ".DS_Store", "__*__"], help='ignore files matching this pattern')
    parser.add_argument('--install', dest='install', action='store_true', default=False, help='run "install.sh" script in toplevel directory')

    parser.add_argument('-t', '--target', dest='target', default=os.getenv('HOME'), help='target directory')

    parser.add_argument("dirs", metavar="dir", type=str, nargs='+', help="src to link")

    args = parser.parse_args()

    target = args.target
    if target is None:
        print('No target directory specified')
        sys.exit(1)

    action_func = None
    run_func = None

    if args.unlink:
        action_func = my_remove
        if args.dry_run:
            action_func = dry_remove
        if args.force:
            action_func = force_remove
    elif args.relink:
        action_func = partial(perform_relink, symlink_func=my_symlink, remove_func=my_remove)
        if args.dry_run:
            action_func = partial(perform_relink, symlink_func=dry_symlink, remove_func=dry_remove)
        if args.force:
            action_func = partial(perform_relink, symlink_func=my_symlink, remove_func=force_remove)
    else:
        action_func = my_symlink
        if args.dry_run:
            action_func = dry_symlink
        if args.force:
            action_func = partial(perform_relink, symlink_func=my_symlink, remove_func=force_remove)
        if args.install:
            run_func = my_run
            if args.dry_run:
                run_func = dry_run

    for dir in args.dirs:
        link_dir(pathlib.Path(dir), pathlib.Path(target), args.ignore, action_func, run_func)


if __name__ == '__main__':
    main()
